### ISSUE TITLE
bug: `dev.url` hook has incorrect default value

### ISSUE THREAD

**Issue by cthom-dev** [roots/bud#1250]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

By default bud will serve at the following address:
host: localhost
port: 3000

If port 3000 is already used a new port will be dynamically selected.

### Actual Behavior

Even when port 3000 isn't being used, a new port will be dynamically selected.

When using Docker, the dev url is therefore unreachable as random port isn't being exposed.

### Steps To Reproduce

1. lando yarn dev
1.
1.

### version

@roots/bud": "5.6.2"

### What package manager are you using?

yarn classic

### version

v1.22.18

### Are you using pnpm?

- [ ] yes
- [X] no

### Configuration

```zsh
/**
 * @typedef {import('@roots/bud').Bud} bud
 *
 * @param {bud} app
 */
module.exports = async (app) => {
  app
    /**
     * Application entrypoints
     *
     * Paths are relative to your resources directory
     */
    .entry({
      app: ['@scripts/app', '@styles/app'],
      editor: ['@scripts/editor', '@styles/editor'],
    })

    /**
     * These files should be processed as part of the build
     * even if they are not explicitly imported in application assets.
     */
    .assets('images')

    /**
     * These files will trigger a full page reload
     * when modified.
     */
    .watch('resources/views/**/*', 'app/**/*')

    /**
     * Target URL to be proxied by the dev server.
     *
     * This is your local dev server.
     */
    .proxy('https://sagetest.test');

};
```

### Relevant .budfiles

```

// .lando.yml

name: sagetest
env_file:
  - .env
recipe: wordpress
proxy:
  appserver_nginx:  # Optional: if you exclude this, Lando will serve it as bedrock.lndo.site
    - sagetest.test
  mailhog:
    - mail.sagetest.test
  theme:  # Optional: add this if you include the Sage specific config down below
    - localhost:3000
    - localhost:3001
config:
  php: '8.0'
  composer_version: 2-latest
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true

# Add the following if you plan to use Sage as a starter theme
services:
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver_nginx
  theme:
    type: node:16
    overrides:
      ports:
        - 3000:3000
        - 3001:3001
tooling:
  yarn:
    service: theme
```
