### ISSUE TITLE
[Feature request] Bud.serve configure different listen and rewrite addresses

### ISSUE THREAD

**Issue by noahott** [roots/bud#1318]
I'm trying to get Bud to work properly while using [Lando](https://lando.dev/) (Docker). In order to do this I'd like a way to specify different addresses and ports for the dev server to listen on, and a different address and port for to inject the dev scripts and to rewrite intercepted URLs.

Currently, in order for the `bud dev` to URL to be accessible outside of the container, bud.config.js must be configured for bud serve to listen on all addresses  like this:
```
bud.proxy('http://bedrock.lndo.site')
.serve('http://0.0.0.0:3000');
```
Lando is then configured (via .lando.yml) to map a domain to the theme container with bud:
```
name: lando-bedrock
recipe: wordpress
config:
  webroot: web
proxy:
  appserver:
    - bedrock.lndo.site
  theme:
    - theme.bedrock.lndo.site:3000
services:
  theme:
    type: node:16
```

Lando handles mapping the theme.bedrock.lndo.site domain to the container with bud, and can then be accessed from http://theme.bedrock.lndo.site (on port 80). The problem is that the development scripts are injected as http://0.0.0.0:3000/app.js, for example, and click intercepting does not work and all URLs point back to the proxy URL.

Additional details and discussion on this configuration can be found here: https://discourse.roots.io/t/lando-bud-sage-configuration/22740/2
