### ISSUE TITLE
[bug] Fonts gives incorrect url in dev mode on localhost urls

### ISSUE THREAD

**Issue by Striffly** [roots/bud#1840]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

Sometimes we have to use the proxying URL (`mywebsite.localhost`) in dev mode to develop some features (integration of recaptcha for example).
All assets load correctly (JS / CSS / medias / ...), except the fonts. The associated path points to a root font folder (`/fonts/NeueMachina.woff2`), and not to the folder where the font are copied (`/app/themes/sages/public/fonts`), unlike other assets.

[Some topics](https://discourse.roots.io/t/fonts-gives-incorrect-url-in-dev-mode-since-5-7-0-release/22850/2) seemed to indicate that using a path like this seemed to work for a while.
```css
@font-face {
  font-family: "DM Sans";
  src: local('DM Sans'),
    url("~@fonts/DMSans/DMSans-Regular.ttf") format("ttf");
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}
```

However, even using this code doesn't seem to solve the problem.

### Expected Behavior

Fonts path begin with `/app/themes/sage/public/fonts` (aliased `~@fonts`)

### Actual Behavior

Fonts path begin with `/fonts`

### Steps To Reproduce

1. Run `bud dev`
1. Go to any Wordpress page.

### version

6.5.3

### What package manager are you using?

yarn

### version

1.22.18
