### ISSUE TITLE
[request] Invalidate build cache when bud.config.js is modified or prompt user to `bud clean`

### ISSUE THREAD

**Issue by talss89** [roots/bud#2187]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### The feature

Check the mtime or hash of `bud.config.js`, compare to last build, and if different, run `bud clean` before build.

Or, perhaps, a less intrusive approach:

Raise a prompt when building with a 'stale' bud.config.js, asking the user to run `bud clean`

### Use case

Currently, updating `bud.config.js` doesn't appear to invalidate the Bud build cache.

For example, building a project with the default`runtimeOnly` version of Vue 3, then adding `app.set('runtimeOnly', false)`, then rebuilding, results in the `runtimeOnly` Vue bundle being included, not the full library. [This was a factor in a user's problem on Discourse](https://discourse.roots.io/t/error-when-compiling-assets-after-adding-vue-in-sage-10/24981/10).

### Notes

For those who are used to say,`make` - the idea of cleaning build artefacts is intuitive, but as far as I can see, it's not made clear in the Bud docs or CLI output.

Logically, my thoughts are that if the build configuration changes (`bud.config.js`), build cache should be invalidated, as it is built upon the build configuration itself. Perhaps I've got that wrong.

**Comment by kellymears** [comment]
Thanks for the excellent issue. Also, great timing!

Hopefully I release bud 6.12.0 tomorrow which addresses this and some other related module resolution and performance issues (`nightly` should have the fix in place now).

I'll detail the three changes I made here. They might seem tangential but I think it's obvious that they're related improvements.

1. When bud is bootstrapping it creates hashes for files in the project root and config directory. These hashes are written to `.budfiles/checksum.yml`. 

```yml
.env: fcaca18d0d59f3e9b8da38726a40af5892c9b4f7
.gitignore: 911ec851bb65a8347c1f686ca0ee3461f87daeba
.eslintrc.js: ed7ef0bf11932aa4c0fc92a0a94d1b8cddcd8894
bud.config.mjs: a9043b5aebc034eeb0b81216f6f66e79160c081c
docker-compose.yml: ed426a574123f2a3ca058cb9f9d912c7a560843f
tailwind.config.cjs: 51543eba8feb62aed3aa8af2aa436e1bd8f5b348
package.json: 0cd0314a3bd9a1cb3f5a9e674632515d399aff1b
tsconfig.json: 16277e37b29669bbf63d3d61b25e45f005278657
```

2. `bud.module` writes resolved paths to `.budfiles/resolutions.yml`

```yml
version: 0.0.0
resolutions:
  # ...
  '@roots/bud-support/css-loader': >-
    /Users/kellymears/code/git/roots/bud/sources/@roots/bud-support/lib/css-loader/index.cjs
  swc-loader: /Users/kellymears/code/git/roots/bud/node_modules/swc-loader/src/index.js
  postcss-import: /Users/kellymears/code/git/roots/bud/node_modules/postcss-import/index.js
  postcss-nested: /Users/kellymears/code/git/roots/bud/node_modules/postcss-nested/index.js
  postcss-preset-env: >-
    /Users/kellymears/code/git/roots/bud/node_modules/postcss-preset-env/dist/index.mjs
  postcss-loader: /Users/kellymears/code/git/roots/bud/node_modules/postcss-loader/dist/cjs.js
  tailwindcss: /Users/kellymears/code/git/roots/bud/node_modules/tailwindcss/lib/index.js
  tailwindcss/nesting/index.js: >-
    /Users/kellymears/code/git/roots/bud/node_modules/tailwindcss/nesting/index.js
  webpack: /Users/kellymears/code/git/roots/bud/node_modules/webpack/lib/index.js
  # ...
```

Module lookup is a little slow right now because in order to allow overrides bud.js needs to try to resolve modules in this order:

- the project context (direct dependency)
- the extension / service context (built-in)

So, there are a lot of necessary but unneeded resolution attempts in <= 6.11.0 in order to resolve the correct package when a user overrides it. But with this cache we can skip those checks. 

_Unless_ the `package.json` sha1 is a mismatch. In that case the `resolutions.yml` cache gets wiped early so that `bud.module` resolves everything again fresh. 

3. `bud.cache` uses these hashes to construct a cache identifier

It was already doing this but maybe there was a race condition or something wonky with it, I'm not sure. I've noticed cached builds weren't perfectly invalidated as well. Regardless,  all hashes from files that contain `bud` as a substring and `package.json` are hashed together and output as a base64 string to serve as a unique identifier of the build dependencies and installed modules. It also factors in command line arguments (but excludes CLI args which in the current version of bud will invalidate the cache needlessly: `--log`, `--notify`, etc.) 

These three changes should result in more reliable cache invalidation, faster module resolution and more assurance that the desired package is being resolved from the package manager store 🤞🏼. Hopefully we won't have to pester the user to run `bud clean` (or use the `--force` flag).
