### ISSUE TITLE
dev url not working with Lando

### ISSUE THREAD

**Issue by cthom-dev** [roots/bud#2297]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

I can reach example.test and mail.example.test find but i cant reach theme.example.test:3000.

```

#lando.myl

name: example
env_file:
  - .env
recipe: wordpress
proxy:
  appserver_nginx: # Optional: if you exclude this, Lando will serve it as bedrock.lndo.site
    - example.test
  mailhog:
    - mail.example.test
  theme: # Optional: add this if you include the Sage specific config down below
    - theme.example.test:3000
config:
  php: "8.0"
  composer_version: 2-latest
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true

# Add the following if you plan to use Sage as a starter theme
services:
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver_nginx
  theme:
    type: node:16
tooling:
  yarn:
    service: theme
 ```

```
#bud.config

/**
 * Compiler configuration
 *
 * @see {@link https://roots.io/docs/sage sage documentation}
 * @see {@link https://bud.js.org/guides/configure bud.js configuration guide}
 *
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {
  /**
   * Application assets & entrypoints
   *
   * @see {@link https://bud.js.org/docs/bud.entry}
   * @see {@link https://bud.js.org/docs/bud.assets}
   */
  app
    .entry('app', ['@scripts/app', '@styles/app'])
    .entry('editor', ['@scripts/editor', '@styles/editor'])
    .assets(['images']);

  /**
   * Set public path
   *
   * @see {@link https://bud.js.org/docs/bud.setPublicPath}
   */
  app.setPublicPath('/app/themes/sage/public/');

  /**
   * Development server settings
   *
   * @see {@link https://bud.js.org/docs/bud.setUrl}
   * @see {@link https://bud.js.org/docs/bud.setProxyUrl}
   * @see {@link https://bud.js.org/docs/bud.watch}
   */
  app
    .setUrl(3000)
    .setPublicUrl(`http://theme.example.test:3000`)
    .setProxyUrl(8000)
    .setPublicProxyUrl(`http://example.test`)

    .watch(['resources/views', 'app']);

  /**
   * Generate WordPress `theme.json`
   *
   * @note This overwrites `theme.json` on every build.
   *
   * @see {@link https://bud.js.org/extensions/sage/theme.json}
   * @see {@link https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json}
   */
  app.wpjson
    .set('settings.color.custom', false)
    .set('settings.color.customDuotone', false)
    .set('settings.color.customGradient', false)
    .set('settings.color.defaultDuotone', false)
    .set('settings.color.defaultGradients', false)
    .set('settings.color.defaultPalette', false)
    .set('settings.color.duotone', [])
    .set('settings.custom.spacing', {})
    .set('settings.custom.typography.font-size', {})
    .set('settings.custom.typography.line-height', {})
    .set('settings.spacing.padding', true)
    .set('settings.spacing.units', ['px', '%', 'em', 'rem', 'vw', 'vh'])
    .set('settings.typography.customFontSize', false)
    .useTailwindColors()
    .useTailwindFontFamily()
    .useTailwindFontSize()
    .enable();
};
```

```
# lando yarn dev

╭─ server
│
├─ proxy: http://example.test/
├─ dev:   http://theme.example.test:3000/
│
╰─ watching project sources (and 25 other files)
```

### Expected Behavior

reach theme.example.test

### Actual Behavior

cant reach theme.example.test

### Steps To Reproduce

1. lando yarn dev
1.
1.

### version

6.12.2
