### ISSUE TITLE
Sage: url() in @font-face declaration doesn't work

### ISSUE THREAD

**Issue by unlocdavid** [roots/bud#822]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When adding a custom font to a Sage theme Bud build errors out on resolving the font woff/woff2 file. `resolve-url-loader` tries to parse the file instead of just generating the correct path.

#### What have you tried?
I've used different file paths, load the url with and without surrounding quotes, but the same result. In the end I've been using this path: `url(~@fonts/public-sans/public-sans-v5-latin-300.woff2) format('woff2')`

#### What insights have you gained?
Images loaded with `url()` in a `background` property do work as expected. Like in this [example](https://github.com/roots/bud/blob/next/examples/sage/resources/styles/common/global.css) So it should be possible.

#### Possible solutions
Not sure, maybe look at how images are handled and apply it to fonts too.

#### Temporary workarounds
Other than including a stylesheet that's not handled by Bud or using a Google Fonts cdn link no real workarounds are available.

### Steps To Reproduce

1. Add a @font-face declaration in the Sage css like:
```
@font-face {
  font-family: 'Public Sans';
  font-style: normal;
  font-weight: 300;
  src: local(''),
    url(~@fonts/public-sans/public-sans-v5-latin-300.woff2) format('woff2'),
    url(~@fonts/public-sans/public-sans-v5-latin-300.woff) format('woff');
  font-display: swap;
}
```
2. Copy the font files to the `resources/fonts` folder
3. Run `yarn build`

### Expected Behavior

The CSS is compiled without errors and the `@font-face` declarations in `app.css` are present and have the correct url's to the font files.

### Actual Behavior

For every font file an error occurs in the build process saying `resolve-url-loader` has a webpack misconfiguration: webpack or the upstream loader did not supply a source-map

### Relevant Log Output

```shell
WARNING in ./resources/fonts/public-sans/public-sans-v5-latin-300.woff
  Module Warning (from ./node_modules/resolve-url-loader/index.js):
  resolve-url-loader: webpack misconfiguration
    webpack or the upstream loader did not supply a source-map
   @ ./resources/styles/app.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!./resources/styles/app.css 10:36-112
   @ ./resources/styles/app.css

  WARNING in ./resources/fonts/public-sans/public-sans-v5-latin-300.woff2
  Module Warning (from ./node_modules/resolve-url-loader/index.js):
  resolve-url-loader: webpack misconfiguration
    webpack or the upstream loader did not supply a source-map
   @ ./resources/styles/app.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!./resources/styles/app.css 9:36-113
   @ ./resources/styles/app.css
```
```


### Versions

5.0.0-next.18

**Comment by purplefeel** [comment]
I am having the same problem.

**Comment by kellymears** [comment]
We'll include a fix for this in the first release after 5.0.0. 

For now you can handle it yourself in the bud.config.js file. 

```ts
    .tap(({build}) => {
      build.rules.font.setUse([]);
      build.rules.font.setType('asset/resource');
    });
```

Or, you could try inlining the font in your css file, if you prefer.

```ts
    .tap(({build}) => {
      build.rules.font.setUse([]);
      build.rules.font.setType('asset');
      build.rules.font.setParser({dataUrlCondition: {maxSize: 50000}});
    });
```

`bud.tap` returns the `bud` instance so you are free to add this snippet wherever you like in the config file.

It'll work with or without quotes, but I found in testing that the sage stylelint config will throw an error without:

```sh
✘ resources/styles/common/global.css
 5:23  ✖  Expected quotes around "url" function argument  function-url-quotes
```

**Comment by igorhrcek** [comment]
@kellymears that workaround partially resolves the issue. Here is what happens next when you have a following code:
```scss
@font-face {
    font-family: 'Bahnschrift';
    src: local('Bahnschrift'),
        url('../fonts/Bahnschrift/Bahnschrift.woff2') format('woff2'),
        url('../fonts/Bahnschrift/Bahnschrift.woff') format('woff'),
        url('../fonts/Bahnschrift/Bahnschrift.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}
```

When I execute `yarn bud  serve` this is the error that I get:
```bash
<e> [webpack-dev-middleware] Error: Conflict: Multiple chunks emit assets to the same filename Bahnschrift (chunks styles and styles)
<e>     at /Users/igor/Projects/static/node_modules/webpack/lib/Compilation.js:4540:12
<e>     at /Users/igor/Projects/static/node_modules/webpack/lib/Cache.js:85:6
<e>     at /Users/igor/Projects/static/node_modules/webpack/lib/Cache.js:39:11
<e>     at /Users/igor/Projects/static/node_modules/webpack/lib/cache/IdleFileCachePlugin.js:77:9
<e>     at /Users/igor/Projects/static/node_modules/webpack/lib/Cache.js:88:6
```

The only way to resolve this is to either give a different name to each font file or to only use one font type in `@font-face` declaration.

**Comment by kellymears** [comment]
@igorhrcek good catch. seems like we can't leave it up to webpack to manage the filename duplicates. Fine running `bud build` but `bud serve` gives me the same error.

Here's an updated patch that works in development as well:

```ts
.tap(({build}) => {
  build.rules.font.setUse([]);
  build.rules.font.setType('asset/resource');
  build.rules.font.setGenerator((app) => ({
    filename: `assets/[name][ext]`,
  }));
});
```

i'll update #860 to account for this. thanks, again.

**sidenote** 

if preferred you can swap out your relative path to the font files with the `@fonts` alias. arguably easier to read and if you move your font-face declaration into a different dir you won't need to update the paths.

```css
@font-face {
  font-family: Bahnschrift;
  src: local('Bahnschrift'),
    url('@fonts/Bahnschrift/Bahnschrift.woff2') format('woff2'),
    url('@fonts/Bahnschrift/Bahnschrift.woff') format('woff'),
    url('@fonts/Bahnschrift/Bahnschrift.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}
```
